README.md
The README.md was updated for your better understanding when installing and using the project locally.
=> Update readme to improve understanding of the project installation

templates/plugin/CakeLte/layout/top-nav.php
movil before:
movil after:
pc before:
pc after:
=> improve navbar responsive and add logout link on navbar toggle in student profile

src/Enum/ActionColor.php
change the color of the button to a more visible one
after:
before:
=> change button colors of  'ver registro' , 'ver proyectos'

plugins/Manager/tests/TestCase/Controller/AreasControllerTest.php, src/Console/Installer.php
add directory to be writable to create the logo file: 
'files',
'files/areas',
'files/students'
delete line print html in log test.
=> add directory to be writable and delete line print html in log test

templates/cell/Forms/register.php
before in mobile:
after in mobile:
=> improve responsive design of the form in student/register (mobile first)

templates/cell/TrackingView/display.php
before in mobile:
after in mobile:
=> improve responsive design view student/trainer collapse button 'agregar actividad'

templates/plugin/BootstrapUI/element/flash/default.php
=> feat: Set timeout to flash message

.github/workflows/ci.yml, composer.lock
=> Develop: next release

templates/Error/error400.php, templates/Error/error500.php, templates/Student/element/stages/register/in-progress.php, templates/layout/error.php
Desktop and Mobile view
```
modified:   templates/Error/error400.php
modified:   templates/Error/error500.php
modified:   templates/Student/element/stages/register/in-progress.php
modified:   templates/layout/error.php
```
=> fixed: bug in lapses inactive - new templates error

templates/Admin/Institutions/edit_project.php
=> fixed: bug in button cancel of edit project

src/Controller/Admin/InstitutionsController.php, templates/Admin/Students/index.php, templates/Admin/Tutors/index.php
=> FIX: Responsive a Vistas Admin/Tutores y Estudiantes

src/Application.php, templates/Student/Dashboard/index.php, tests/Factory/StudentAdscriptionFactory.php, tests/TestCase/Controller/Student/DashboardEndingController.php, tests/TestCase/Controller/Student/DocumentsControllerTest.php, tests/Traits/CommonTestTrait.php
=> tests: create commonTestTrait, new DashEndingController

tests/TestCase/Controller/Student/DashboardResultsControllerTest.php
A test was added to the student results part of the dashboard
=> add test for results

templates/plugin/CakeLte/element/sidebar/menu.php
=> feat: Icons in Dashboard

templates/Admin/Reports/index.php
=> feat: added views field and wrap, function show fields

src/Utility/FilterTenantUtility.php
=> fix: fix bug when tenantFilter mellado

tests/TestCase/Controller/Student/DashboardControllerRegisterTest.php
=> Registertest

tests/TestCase/Controller/Student/DashboardControllerAdscriptionTest.php, tests/TestCase/Controller/Student/DashboardControllerRegisterTest.php
=> test: DashboardAdscriptionTest

tests/TestCase/Controller/Student/DashboardControllerRegisterTest.php
=> Registertest with LapseDates

tests/Factory/StudentTrackingFactory.php, tests/TestCase/Controller/Student/DashboardControllerAdscriptionTest.php, tests/TestCase/Controller/Student/DashboardControllerRegisterTest.php, tests/TestCase/Controller/Student/DashboardControllerTrackingTest.php
=> test: DashboardTesttracking

templates/Admin/Reports/tenant.php, templates/cell/ReportTenant/projects.php
=> fix: css in tenant report - added cols spacing into table

src/Model/Entity/StudentStage.php, src/Policy/StudentStagePolicy.php
=> fix: add adscription open count to filter closeStage/printStage

tests/TestCase/Controller/Student/DashboardControllerTrackingTest.php
=> change: AdcriptionStatus to CLOSED

templates/cell/TrackingView/display.php
=> fix: css in columns table dashboard tracking
